"use client";
import { C } from "@/components/ui";

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 640, margin: "0 auto", padding: "40px 24px", color: C.t2, fontSize: 14, lineHeight: 1.8 }}>
      <a href="/" style={{ color: C.purple, fontSize: 13, textDecoration: "none" }}>← Back</a>
      <h1 style={{ fontFamily: "'Syne'", fontSize: 28, fontWeight: 800, color: C.t1, marginTop: 16, marginBottom: 24 }}>Terms of Service</h1>
      <p>Last updated: April 2026</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>1. Acceptance</h2>
      <p>By using Bio-Hacked, you agree to these terms. If you disagree, do not use the platform.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>2. Service Description</h2>
      <p>Bio-Hacked is an AI-powered nutrition, coaching, and community platform. It is not a substitute for medical advice. Consult a healthcare professional before starting any diet or exercise program.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>3. User Accounts</h2>
      <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>4. Coach-Client Relationship</h2>
      <p>Coaches on Bio-Hacked are independent professionals. Bio-Hacked does not employ coaches and is not liable for advice given by coaches on the platform.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>5. AI-Generated Content</h2>
      <p>Meal plans and recipes are generated by AI and should be reviewed before following. Bio-Hacked is not liable for adverse reactions to AI-generated nutritional advice.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>6. Payments</h2>
      <p>Premium subscriptions are processed via PayFast in South African Rand (ZAR). Cancellations take effect at the end of the billing period.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>7. Data Handling</h2>
      <p>See our <a href="/privacy" style={{ color: C.purple }}>Privacy Policy</a> for how we handle your data under POPIA.</p>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: C.t1, marginTop: 24 }}>8. Termination</h2>
      <p>We may suspend or terminate accounts that violate these terms or engage in harmful behaviour on the platform.</p>
    </div>
  );
}
